name: Build and Push NGINX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dbeilin-playground/nginx

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Enhanced version generation with cherry-pick detection
    - name: Generate version
      id: version
      run: |
        BASE_VERSION="v1.0.$(date +%Y%m%d%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)"
        BRANCH_NAME="${GITHUB_REF#refs/heads/}"
        
        # Check if this is a cherry-pick branch
        if [[ "$BRANCH_NAME" == cherrypick/* ]]; then
          # Extract fix description from branch name
          FIX_DESC=$(echo "$BRANCH_NAME" | sed 's/cherrypick\/prod-[0-9]*-//')
          VERSION="${BASE_VERSION}-cherrypick-${FIX_DESC}"
          echo "is_cherrypick=true" >> $GITHUB_OUTPUT
          echo "Cherry-pick detected: $VERSION"
        else
          VERSION="$BASE_VERSION"
          echo "is_cherrypick=false" >> $GITHUB_OUTPUT
          echo "Regular build: $VERSION"
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        target: production
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        build-args: |
          VERSION=${{ steps.version.outputs.version }}
          BUILD_DATE=${{ github.event.head_commit.timestamp }}
          GIT_COMMIT=${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Docker image (pprof)
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        target: pprof
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}-pprof
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-pprof
        build-args: |
          VERSION=${{ steps.version.outputs.version }}
          BUILD_DATE=${{ github.event.head_commit.timestamp }}
          GIT_COMMIT=${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output image details
      run: |
        echo "🚀 Successfully built and pushed:"
        echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}"
        echo "Pprof: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}-pprof"
        if [[ "${{ steps.version.outputs.is_cherrypick }}" == "true" ]]; then
          echo "🍒 CHERRY-PICK BUILD - Will be detected by Kargo cherry-pick system"
        fi

    # Only update STG for main branch builds, skip for cherry-picks
    - name: Checkout config repository
      if: steps.version.outputs.is_cherrypick != 'true'
      uses: actions/checkout@v4
      with:
        repository: dbeilin-playground/config
        token: ${{ secrets.PAT_TOKEN }}
        path: devops-config
        ref: main

    - name: Update STG values-image.yaml
      if: steps.version.outputs.is_cherrypick != 'true'
      run: |
        cd devops-config
        # Update the image tag in STG environment
        sed -i 's/tag: .*/tag: ${{ steps.version.outputs.version }}/' argocd/stg/stg-be/nginx/values-image.yaml
        echo "Updated STG values-image.yaml with tag: ${{ steps.version.outputs.version }}"
        cat argocd/stg/stg-be/nginx/values-image.yaml

    - name: "Auto create pull-request"
      if: steps.version.outputs.is_cherrypick != 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        path: devops-config
        token: ${{ secrets.PAT_TOKEN }}
        title: "[GHA] [${{ github.event.repository.name }}] on merge ${{ github.sha }} by ${{ github.actor }}"
        commit-message: "[Github Action] [repo: ${{ github.event.repository.name }}] on merge ${{ github.sha }} by <@${{ github.actor }}>"
        branch: ${{ github.event.repository.name }}
        branch-suffix: timestamp
        delete-branch: true
        body: |
          Changes by @${{ github.actor }} in `${{ github.event.repository.name }}`:
          - Triggered by: @${{ github.triggering_actor }}
          - Commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          - Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          - Run attempt: ${{ github.run_attempt }}
          - Updated image tag to: ${{ steps.version.outputs.version }}
        labels: |
          automated_pr

    # Cherry-pick specific notification
    - name: Cherry-pick build notification
      if: steps.version.outputs.is_cherrypick == 'true'
      run: |
        echo "Cherry-pick build completed!"
        echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}"
        echo "Branch: ${{ steps.version.outputs.branch_name }}"
